baseURL = "https://www.danvanwijk.com"

title = "Dan van Wijk"
languageCode = "en-us"
defaultContentLanguage = "en"

theme = "axiom"

paginate = 7
canonifyURLs = false
summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/:title"

[params]
mainSections = ["posts"]
copyrightYear = "2020"
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "January 2, 2006"
highlight = "dark"

[params.brand]
domain = "danvanwijk.com"
email = "hello@danvanwijk.com"

[params.social]
facebook = ""
github = "https://github.com/danvanwijk"
instagram = ""
linkedin = "https://www.linkedin.com/in/dvanwijk"
pinterest = ""
stackoverflow = ""
twitter = ""
youtube = ""
strava = "https://www.strava.com/athletes/danvanwijk"
footer = ["github", "linkedin", "strava"]

[params.services]
googleAnalyticsId = ""
googleTagManagerId = ""
googleAdsId = ""
googleAdsenseId = ""
googleAdsenseAdSlotId = ""
googleAdsenseLoad = ""
googleAdsConversionId = ""
googleAdsConversionValue = 0
facebookApp = ""
facebookPixel = ""
disqusShortname = ""

[params.logo]
inline = true
path = ""

[params.image]
width = "2048"
height = "1024"
faviconIco = "favicon.ico"
faviconAlt = "favicon.png"
icon1To1 = "favicon.png"
icon2To1 = "favicon.png"
default = ""

[params.font]
type = ""
path = ""
files = []

[params.cdn]
provider = "local"
type = "image"

[params.cloudinary]
host = "https://res.cloudinary.com/CLOUD_NAME/"
version = ""
image = "image/upload/"
raw = "raw/upload/"
video = "video/upload/"

[params.cloudinary.presets]
base = "f_auto,q_auto/"
page = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
# lineNos = true
# lineNumbersInTable = false

[menu]
[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.main]]
url = "/journal/"
name = "Journal"
weight = 2

[[menu.main]]
url = "/about/"
name = "About"
weight = 3

[[menu.foot]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.foot]]
url = "/journal/"
name = "Journal"
weight = 2

[[menu.foot]]
url = "/about/"
name = "About"
weight = 3

[[menu.foot]]
url = "/contact/"
name = "Contact"
weight = 4

[[menu.foot]]
url = "/privacy/"
name = "Privacy"
weight = 4

[languages]
[languages."en"]
weight = 1
languageName = "English"
